### ISSUE TITLE
Error in VSCode output pane when trying to get autocompletions

### ISSUE THREAD

**Issue by bakerac4** [typed-ember/glint#124]
When I go into my controllers template, and type `{{this.}}` I see the following error in the output pane for Glint Language Server in VSCode

```
[Error - 12:00:04 PM] Error: Could not find source file: '/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/app/pods/admin/language/template.hbs'.
    at getValidSourceFile (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/typescript/lib/typescript.js:147056:29)
    at Object.getCompletionsAtPosition (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/typescript/lib/typescript.js:147289:80)
    at GlintLanguageServer.getCompletions (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/@glint/core/lib/language-server/glint-language-server.js:114:40)
    at /Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/@glint/core/lib/language-server/binding.js:41:51
    at captureErrors (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/@glint/core/lib/language-server/binding.js:76:24)
    at /Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/@glint/core/lib/language-server/binding.js:41:16
    at /Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/vscode-languageserver/lib/common/server.js:678:20
    at handleRequest (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/vscode-jsonrpc/lib/common/connection.js:405:41)
    at processMessageQueue (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/vscode-jsonrpc/lib/common/connection.js:286:17)
    at Immediate._onImmediate (/Users/adambaker/Development/gavant/PEP-Web-User-Interface/pep/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
```

It also seems to occur if you hover on that code as well.

**Comment by dfreeman** [comment]
Got it, thanks for writing this up! Should be a quick fix, I think.
