### ISSUE TITLE
TypeScript compiler crashes

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/glint#216]
```hbs
{{foo-bar type "in"}}
```

That's the full template. Both `foo-bar` and `type` are undefined and unknown. Running `glint` leads to:

```
/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:2546
            throw e;
            ^

Error: Debug Failure.
    at /home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:19487:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:19487:21)
    at Object.createDetachedDiagnostic (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:19503:20)
    at parseErrorAtPosition (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:30898:42)
    at parseErrorAt (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:30905:13)
    at parseErrorAtCurrentToken (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:30892:13)
    at parseErrorForInvalidName (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:31130:17)
    at parseErrorForMissingSemicolonAfter (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:31102:21)
    at parseExpressionOrLabeledStatement (/home/boris/code/glint-issue/node_modules/typescript/lib/typescript.js:34992:21)
```

Using the latest TypeScript compiler - 4.4.3.

Note that changing the variable `type` to (I think) anything else fixes the issue - i.e. the compiler doesn't blow up but rather gives correct errors about `foo-bar` and `asd` not existing in `Globals`.

**Comment by dfreeman** [comment]
Should be fixed by #250
