### ISSUE TITLE
envFunction is not a function

### ISSUE THREAD

**Issue by NullVoxPopuli** [typed-ember/glint#319]
Error:
```
❯ node_modules/.bin/glint
<repo>/node_modules/.pnpm/@glint+config@0.8.0/node_modules/@glint/config/lib/environment.js:134
        let config = envFunction(envUserConfig !== null && envUserConfig !== void 0 ? envUserConfig : {});
                     ^

TypeError: envFunction is not a function
    at loadMergedEnvironmentConfig (<repo>/node_modules/.pnpm/@glint+config@0.8.0/node_modules/@glint/config/lib/environment.js:134:22)
    at Function.load (<repo>/node_modules/.pnpm/@glint+config@0.8.0/node_modules/@glint/config/lib/environment.js:29:22)
    at new GlintConfig (<repo>/node_modules/.pnpm/@glint+config@0.8.0/node_modules/@glint/config/lib/config.js:19:59)
    at findConfig (<repo>/node_modules/.pnpm/@glint+config@0.8.0/node_modules/@glint/config/lib/index.js:36:16)
    at loadConfig (<repo>/node_modules/.pnpm/@glint+config@0.8.0/node_modules/@glint/config/lib/index.js:21:18)
    at Object.<anonymous> (<repo>/node_modules/.pnpm/@glint+core@0.8.0/node_modules/@glint/core/lib/cli/index.js:38:45)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)}
```

This happened after setting up glint in a brand new app with no components.

Here is a repro (at this specific commit):

**Comment by NullVoxPopuli** [comment]
@dfreeman pointed out that I was missing `glint-environment-ember-template-imports` in my repro.  which explains the above error.

So _now_ I guess this issue is about missing environments?
