### ISSUE TITLE
Using a JS keyword as a block parameter name results in an internal error

### ISSUE THREAD

**Issue by LanceStasinski** [typed-ember/glint#444]
When I use the result of a method as a temporary variable in the `{{#let}}` helper, I get this error:

```bash
Error: Internal error: offset out of bounds
    at assert (~/node_modules/@glint/transform/lib/util.js:10:15)
    at TransformedModule.determineOriginalOffsetAndSpan (~/node_modules/@glint/transform/lib/template/transformed-module.js:87:27)
    at TransformedModule.getOriginalRange (~/node_modules/@glint/transform/lib/template/transformed-module.js:39:28)
    at rewriteDiagnostic (~/node_modules/@glint/transform/lib/diagnostics/rewrite-diagnostic.js:20:61)
    at TransformManager.rewriteDiagnostic (~/node_modules/@glint/core/lib/common/transform-manager.js:192:69)
    at TransformManager.rewriteDiagnostics (~/node_modules/@glint/core/lib/common/transform-manager.js:116:66)
    at GlintLanguageServer.getDiagnostics (~/node_modules/@glint/core/lib/language-server/glint-language-server.js:89:14)
    at Timeout._onTimeout (~/node_modules/@glint/core/lib/language-server/pool.js:74:48)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```

example.ts
```typescript
interface SwitchValue {
    code: string | number,
    name: string
}

@tracked switchOff = {
  code: 0,
  name: 'off'
}

@tracked switchOn = {
  code: 1,
  name: 'on'
}

@action getSwitch(position: 'off' | 'on'): SwitchValue | undefined {
    return position === 'off' ? this.switchOff : this.switchOn
 }
```

example.hbs
```hbs
<div>
  {{#let (this.getSwitch 'on') as |switch| }}
    <div>{{switch.name}}</div>
  {{/let}}
</div>
```

I'm using `"@glint/core": "^0.9.4"`, `"@glint/environment-ember-loose": "^0.9.5"`, `"@gavant/glint-template-types": "0.1.5"`, `"ember-cli": "~4.5.0"`

**Comment by dfreeman** [comment]
Thanks for the report, @LanceStasinski!

Looking into this, I think what you're hitting is the fact that `switch` is a keyword in JS/TS. We definitely shouldn't crash here, but in the meantime you should be able to pick a different name for your block parameter to work around the issue.

**Comment by LanceStasinski** [comment]
@dfreeman Good catch, that does seem to be the problem. Thanks!
