### ISSUE TITLE
`${` in templates breaks Glint

### ISSUE THREAD

**Issue by chancancode** [typed-ember/glint#707]
No interpolated values in template strings

Similar to https://github.com/NullVoxPopuli/ember-eslint-parser/issues/75

Haven't checked if the code in #655 would have avoided this issue

**Comment by tcjr** [comment]
Seeing this in glint 2 alpha 4.

```gjs
<template>
  Cost: ${{@cost}}
</template>
```


Causes this:

```
[lint:types] file:///Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/@glint+core@2.0.0-alpha.4_typescript@5.9.2/node_modules/@glint/core/lib/transform/util.js:6
[lint:types]         throw new Error(typeof message === 'string' ? message : message());
[lint:types]               ^
[lint:types] 
[lint:types] Error: No interpolated values in template strings
[lint:types]     at assert (file:///Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/@glint+core@2.0.0-alpha.4_typescript@5.9.2/node_modules/@glint/core/lib/transform/util.js:6:15)
[lint:types]     at calculateTaggedTemplateSpans (file:///Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/@glint+core@2.0.0-alpha.4_typescript@5.9.2/node_modules/@glint/core/lib/transform/template/inlining/tagged-strings.js:15:9)
[lint:types]     at visit (file:///Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/@glint+core@2.0.0-alpha.4_typescript@5.9.2/node_modules/@glint/core/lib/transform/template/rewrite-module.js:76:30)
[lint:types]     at visitNode (/Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:95057:19)
[lint:types]     at visitEachChildOfComputedPropertyName (/Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:95318:26)
[lint:types]     at Object.visitEachChild (/Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:95305:33)
[lint:types]     at visit (file:///Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/@glint+core@2.0.0-alpha.4_typescript@5.9.2/node_modules/@glint/core/lib/transform/template/rewrite-module.js:85:23)
[lint:types]     at visitNode (/Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:95057:19)
[lint:types]     at visitEachChildOfPropertyDeclaration (/Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:95362:26)
[lint:types]     at Object.visitEachChild (/Users/tcjr/dev/tcjr/blocky/node_modules/.pnpm/typescript@5.9.2/node_modules/typescript/lib/typescript.js:95305:33)
[lint:types] 
[lint:types] Node.js v24.3.0
[lint:types]  ELIFECYCLE  Command failed with exit code 1.
[lint:types] pnpm run lint:types exited with code 1
```

**Comment by NullVoxPopuli** [comment]
Seems fixed now -- closing 

<img width="448" height="143" alt="Image" src="https://github.com/user-attachments/assets/cd7f38eb-79b5-4ed9-9aa7-1138847b3378" />
