### ISSUE TITLE
Publishing prerelease version of VSCode extension?

### ISSUE THREAD

**Issue by davidtaylorhq** [typed-ember/glint#775]
We're using the 'unstable' release of glint, and it works much better for us than the 'stable' version. However, to get things working in VSCode, we have to manually build & install the glint VSCode extension.

Would it be possible to publish a ['pre-release' version](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions) of the VSCode plugin, to make it easier for people to start experimenting with the Volar-based implementation?

Happy to help with getting the automation set up, but I'd need help from someone with the necessary VSCode-marketplace credentials.

**Comment by machty** [comment]
@davidtaylorhq I'm not opposed to this, but could you share what issues you're running into using the stable VSCode Plugin with the unstable Glint LS? I've been using this configuration and there are few things like "Organize Imports" that don't work, but are there other showstoppers I'm unaware of?

**Comment by davidtaylorhq** [comment]
Unfortunately I wasn't able to consistently reproduce it, but this is the kind of error we were seeing:

```
Glint encountered an error computing diagnostics for this file. This is likely a bug in Glint; please file an issue, including any code and/or steps to follow to reproduce the error.

Error: Debug Failure. False expression: Script kind should match provided ScriptKind:1 and sourceFile.scriptKind: 3, !entry: false
    at getDocumentRegistryEntry (/Users/david/discourse/discourse/node_modules/.pnpm/typescript@5.6.3/node_modules/typescript/lib/typescript.js:140976:11)
    at Object.releaseDocumentWithKey (/Users/david/discourse/discourse/node_modules/.pnpm/typescript@5.6.3/node_modules/typescript/lib/typescript.js:141070:19)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/Users/david/discourse/discourse/node_modules/.pnpm/typescript@5.6.3/node_modules/typescript/lib/typescript.js:149935:30)
    at tryReuseStructureFromOldProgram (/Users/david/discourse/discourse/node_modules/.pnpm/typescript@5.6.3/node_modules/typescript/lib/typescript.js:125467:59)
    at createProgram (/Users/david/discourse/discourse/node_modules/.pnpm/typescript@5.6.3/node_modules/typescript/lib/typescript.js:124867:23)
    at synchronizeHostDataWorker (/Users/david/discourse/discourse/node_modules/.pnpm/typescript@5.6.3/node_modules/typescript/lib/typescript.js:149871:15)
```
One this happened, a full restart of the VSCode extension host was required. ('restart glint server' wasn't enough)

We've since managed to get the stable version of Glint working on our codebase, so that's solved the immediate problem.
