### ISSUE TITLE
Seems to Hang in VSCode

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#94]
I can run `yarn glint` but the linting in VSCode just seems to be stuck with outdated warnings.

**Comment by wagenet** [comment]
I noticed that I had a high CPU `node` process. I force quit it and got this in the output in VSCode:

```
[Error - 5:40:14 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
	at Object.dispose (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-languageclient/lib/common/client.js:73:35)
	at LanguageClient.handleConnectionClosed (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
	at LanguageClient.handleConnectionClosed (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-languageclient/lib/node/main.js:155:15)
	at closeHandler (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
	at CallbackList.invoke (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
	at CallbackList.invoke (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageReader.fireClose (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
	at Socket.<anonymous> (/Users/peterwagenet/.vscode/extensions/typed-ember.glint-vscode-0.4.1/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
```

**Comment by dfreeman** [comment]
Based on our conversation in Discord, I marked #95 as resolving this. Aiming to have that out in a release in the near future 😄
